// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aypnelqopfcdgbncxgyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5cG5lbHFvcGZjZGdibmN4Z3lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDM0MDYsImV4cCI6MjA2ODY3OTQwNn0.NgTUyu9g9yh_bftBqPmdYDYIk5WeJWI6Vrbqzjrv9pA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});